### ISSUE TITLE
Questions about the dataset

### ISSUE THREAD

**Issue by WuYunjin** [nkicsl/DDR-dataset#1]
Hi,
It's a really great dataset,
But after I downloaded the DDR data from Baidu Drive,  I found the file "DDR-dataset.zip.001" seems to have contained all images mentioned in the paper.
So I wonder what is the rest files like "DDR-dataset.zip.002" or "DDR-dataset.zip.003" for?

**Comment by guomugong** [comment]
> Hi,
> It's a really great dataset,
> But after I downloaded the DDR data from Baidu Drive, I found the file "DDR-dataset.zip.001" seems to have contained all images mentioned in the paper.
> So I wonder what is the rest files like "DDR-dataset.zip.002" or "DDR-dataset.zip.003" for?

The dataset was compressed in volumes, and it can not be  unzipped without 002,003.
